language: cpp
dist: trusty
os:
  - linux
compiler:  
  - gcc
  - clang




script:
  - echo "Saving current workdir."
  - export CURRENTDIR=`pwd`
  - echo "Make sure cmake >3.3 is available."
  - mkdir cmake-install
  - cd cmake-install
  - wget https://cmake.org/files/v3.9/cmake-3.9.2-Linux-x86_64.sh
  - chmod +x cmake-3.9.2-Linux-x86_64.sh
  - sudo ./cmake-3.9.2-Linux-x86_64.sh --prefix=/usr/local
  - sudo update-alternatives --install /usr/bin/cmake cmake /usr/local/bin/cmake 1 --force
  - cd $CURRENTDIR
  - echo "Preparing environment before compilation"
  - mkdir build
  - cd build
  - cmake -DCMAKE_INSTALL_PREFIX=../install ..
  - make
  - make install

after_success:
  - echo "Everything worked well, will publish executables now to production web server"

